name: Create APK from Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: "latest-master"
          generateReleaseNotes: true
          commit: "master"
          allowUpdates: true
          artifacts: "app/build/outputs/apk/debug/*.apk"
          makeLatest: true
